ARMOR = {
    "Armor_1": {
        "Name": "Armor_1",
        "Class": "Heavy",
        "Color": "Blue",
        "DEX": 50,
        "STR": 50,
        "INT": 0,
        "HASTE": 50,
        "MASTERY": 50,
    },
    "Armor_2": {
        "Name": "Armor_2",
        "Class": "Heavy",
        "Color": "Red",
        "DEX": 100,
        "STR": 100,
        "INT": 0,
        "HASTE": 100,
        "MASTERY": 100,
    },
    "Light_1": {
        "Name": "Light_1",
        "Class": "Heavy",
        "Color": "Blue",
        "DEX": 50,
        "STR": 50,
        "INT": 0,
        "HASTE": 50,
        "MASTERY": 50,
    },
    "Light_2": {
        "Name": "Light_2",
        "Class": "Heavy",
        "Color": "Red",
        "DEX": 100,
        "STR": 100,
        "INT": 0,
        "HASTE": 100,
        "MASTERY": 100,
    },
    "Hat_1": {
        "Name": "Hat_1",
        "Class": "Heavy",
        "Color": "Red",
        "DEX": 10,
        "STR": 10,
        "INT": 0,
        "HASTE": 10,
        "MASTERY": 10,
    },
    "Hat_2": {
        "Name": "Hat_2",
        "Class": "Heavy",
        "Color": "Red",
        "DEX": 20,
        "STR": 20,
        "INT": 0,
        "HASTE": 20,
        "MASTERY": 20,
    },
}
