# First three letters are the type for identifying later

ARMOR = {
    "Armor_1": {
        "Name": "Armor_1",
        "Type": "Armor",
        "Class": "Heavy",
        "Color": "Blue",
        "Armor_value": 50,
        "DEX": 0,
        "STR": 50,
        "INT": 0,
        "HASTE": 50,
        "MASTERY": 50,
    },
    "Armor_2": {
        "Name": "Armor_2",
        "Type": "Armor",
        "Class": "Heavy",
        "Color": "Red",
        "Armor_value": 100,
        "DEX": 0,
        "STR": 100,
        "INT": 0,
        "HASTE": 100,
        "MASTERY": 100,
    },
    "Light_1": {
        "Name": "Light_1",
        "Type": "Armor",
        "Class": "Heavy",
        "Color": "Blue",
        "Armor_value": 50,
        "DEX": 50,
        "STR": 0,
        "INT": 0,
        "HASTE": 50,
        "MASTERY": 50,
    },
    "Light_2": {
        "Name": "Light_2",
        "Type": "Armor",
        "Class": "Heavy",
        "Color": "Red",
        "Armor_value": 100,
        "DEX": 100,
        "STR": 0,
        "INT": 0,
        "HASTE": 100,
        "MASTERY": 100,
    },
}
HATS = {
    "Hat_1": {
        "Name": "Hat_1",
        "Type": "Hat",
        "Class": "Heavy",
        "Color": "Red",
        "Armor_value": 10,
        "DEX": 10,
        "STR": 10,
        "INT": 0,
        "HASTE": 10,
        "MASTERY": 10,
    },
    "Hat_2": {
        "Name": "Hat_2",
        "Type": "Hat",
        "Class": "Heavy",
        "Color": "Red",
        "Armor_value": 20,
        "DEX": 20,
        "STR": 20,
        "INT": 0,
        "HASTE": 20,
        "MASTERY": 20,
    },
}
